// Generates src/lib/schema.gen.ts from the build's api-schema.json — the SAME
// single source of truth that drives the docs site (a.schema). Run via `deno task gen`.
// This replaces the runtime `a.api` discovery the legacy console did by hand.

const ROOT = new URL("..", import.meta.url).pathname;
const candidates = [
  `${ROOT}../docs/api-schema.json`,
  `${ROOT}../publish/api-schema.json`,
];

let raw: string | null = null;
let used = "";
for (const path of candidates) {
  try {
    raw = await Deno.readTextFile(path);
    used = path;
    break;
  } catch {
    /* try next */
  }
}
if (raw == null) {
  console.error(
    `gen-schema: no api-schema.json found in:\n  ${candidates.join("\n  ")}\n` +
      `Build the plugin first (it emits publish/api-schema.json), or run the docs codegen.`,
  );
  Deno.exit(1);
}

interface SchemaEntry {
  key: string;
  description?: string;
  units?: string;
  plotable?: boolean;
  isAction?: boolean;
  alwaysEvaluable?: boolean;
  category?: string;
  returnType?: string;
  params?: string;
  requiresMod?: string;
  deprecated?: boolean;
}

const entries = JSON.parse(raw) as SchemaEntry[];
entries.sort((a, b) => a.key.localeCompare(b.key));

const lit = (s: string | undefined) => JSON.stringify(s ?? "");
const body = entries
  .map(
    (e) =>
      `  ${JSON.stringify(e.key)}: { key: ${lit(e.key)}, name: ${lit(e.description)}, ` +
      `units: ${lit(e.units || "UNITLESS")}, plotable: ${!!e.plotable}, ` +
      `isAction: ${!!e.isAction}, category: ${lit(e.category)}` +
      (e.requiresMod ? `, requiresMod: ${lit(e.requiresMod)}` : "") +
      ` },`,
  )
  .join("\n");

const out = `// AUTO-GENERATED by scripts/gen-schema.ts — do not edit by hand.
// Source: ${used.split("/").slice(-2).join("/")} (${entries.length} endpoints).

export interface ApiEntry {
  key: string;
  name: string;
  units: string;
  plotable: boolean;
  isAction: boolean;
  category: string;
  requiresMod?: string;
}

export const SCHEMA = {
${body}
} as const satisfies Record<string, ApiEntry>;

/** Every base API key the build knows about (e.g. "v.altitude"). */
export type ApiKey = keyof typeof SCHEMA;

export const API_ENTRIES: ApiEntry[] = Object.values(SCHEMA);
`;

await Deno.writeTextFile(`${ROOT}src/lib/schema.gen.ts`, out);
console.log(`gen-schema: wrote ${entries.length} entries -> src/lib/schema.gen.ts`);
