using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace Telemachus.DocGen
{
    [Generator]
    public class TelemetrySchemaGenerator : IIncrementalGenerator
    {
        private const string AttributeFullName = "Telemachus.TelemetryAPIAttribute";

        public void Initialize(IncrementalGeneratorInitializationContext context)
        {
            var pipeline = context.SyntaxProvider
                .ForAttributeWithMetadataName(
                    AttributeFullName,
                    predicate: static (node, _) => node is MethodDeclarationSyntax,
                    transform: static (ctx, ct) => ExtractEntry(ctx))
                .Where(static e => e != null)
                .Select(static (e, _) => e!.Value)
                .Collect();

            context.RegisterSourceOutput(pipeline, static (ctx, entries) =>
            {
                var json = BuildJson(entries);
                var source = new StringBuilder();
                source.AppendLine("// <auto-generated/>");
                source.AppendLine("namespace Telemachus.Generated");
                source.AppendLine("{");
                source.AppendLine("    internal static class TelemetrySchema");
                source.AppendLine("    {");
                // Use a const string with the JSON. Markers allow AfterBuild extraction.
                source.AppendLine("        // SCHEMA_JSON_BEGIN");
                source.Append("        internal const string Json = @\"");
                source.Append(json.Replace("\"", "\"\""));
                source.AppendLine("\";");
                source.AppendLine("        // SCHEMA_JSON_END");
                source.AppendLine("    }");
                source.AppendLine("}");

                ctx.AddSource("TelemetrySchema.g.cs", source.ToString());
            });
        }

        private static TelemetryEntry? ExtractEntry(GeneratorAttributeSyntaxContext ctx)
        {
            var method = ctx.TargetSymbol as IMethodSymbol;
            if (method == null) return null;

            var attr = ctx.Attributes.FirstOrDefault(a =>
                a.AttributeClass?.ToDisplayString() == AttributeFullName);
            if (attr == null) return null;

            var ctorArgs = attr.ConstructorArguments;
            if (ctorArgs.Length < 2) return null;

            var key = ctorArgs[0].Value as string ?? "";
            var description = ctorArgs[1].Value as string ?? "";

            var named = attr.NamedArguments.ToDictionary(
                kv => kv.Key, kv => kv.Value);

            return new TelemetryEntry
            {
                Key = key,
                Description = description,
                Units = GetNamedString(named, "Units") ?? "UNITLESS",
                Plotable = GetNamedBool(named, "Plotable", true),
                IsAction = GetNamedBool(named, "IsAction", false),
                AlwaysEvaluable = GetNamedBool(named, "AlwaysEvaluable", false),
                Category = GetNamedString(named, "Category"),
                ReturnType = GetNamedString(named, "ReturnType"),
                Params = GetNamedString(named, "Params"),
                Since = GetNamedString(named, "Since"),
                RequiresMod = GetNamedString(named, "RequiresMod"),
                Deprecated = GetNamedBool(named, "Deprecated", false),
                DeprecatedMessage = GetNamedString(named, "DeprecatedMessage"),
                Formatter = GetNamedString(named, "Formatter"),
                DeclaringClass = method.ContainingType?.Name ?? "",
                SourceFile = method.Locations.FirstOrDefault()?.SourceTree?.FilePath ?? ""
            };
        }

        private static string GetNamedString(Dictionary<string, TypedConstant> named, string key)
        {
            if (!named.TryGetValue(key, out var tc)) return null;
            if (tc.Value is string s) return s;
            // Handle enum values (like UnitType) — return the constant name
            if (tc.Type?.TypeKind == TypeKind.Enum)
            {
                var members = tc.Type.GetMembers()
                    .OfType<IFieldSymbol>()
                    .Where(f => f.HasConstantValue && Equals(f.ConstantValue, tc.Value));
                var member = members.FirstOrDefault();
                return member?.Name ?? tc.Value?.ToString();
            }
            return tc.Value?.ToString();
        }

        private static bool GetNamedBool(Dictionary<string, TypedConstant> named, string key, bool defaultValue)
        {
            if (!named.TryGetValue(key, out var tc)) return defaultValue;
            return tc.Value is bool b ? b : defaultValue;
        }

        private static string BuildJson(ImmutableArray<TelemetryEntry> entries)
        {
            var sb = new StringBuilder();
            sb.AppendLine("[");

            for (int i = 0; i < entries.Length; i++)
            {
                var e = entries[i];
                sb.Append("  {");
                sb.Append(JsonPair("key", e.Key));
                sb.Append(JsonPair("description", e.Description));
                sb.Append(JsonPair("units", e.Units));
                sb.Append(JsonBoolPair("plotable", e.Plotable));
                sb.Append(JsonBoolPair("isAction", e.IsAction));
                sb.Append(JsonBoolPair("alwaysEvaluable", e.AlwaysEvaluable));

                if (e.Category != null) sb.Append(JsonPair("category", e.Category));
                if (e.ReturnType != null) sb.Append(JsonPair("returnType", e.ReturnType));
                if (e.Params != null) sb.Append(JsonPair("params", e.Params));
                if (e.Since != null) sb.Append(JsonPair("since", e.Since));
                if (e.RequiresMod != null) sb.Append(JsonPair("requiresMod", e.RequiresMod));
                if (e.Deprecated) sb.Append(JsonBoolPair("deprecated", true));
                if (e.DeprecatedMessage != null) sb.Append(JsonPair("deprecatedMessage", e.DeprecatedMessage));
                if (e.Formatter != null) sb.Append(JsonPair("formatter", e.Formatter));

                sb.Append(JsonPair("declaringClass", e.DeclaringClass));
                // Last pair — no trailing comma
                sb.Append("\"sourceFile\": \"");
                sb.Append(EscapeJson(e.SourceFile));
                sb.Append("\"");

                sb.Append("}");
                if (i < entries.Length - 1) sb.Append(",");
                sb.AppendLine();
            }

            sb.Append("]");
            return sb.ToString();
        }

        private static string JsonPair(string key, string value)
        {
            return "\"" + key + "\": \"" + EscapeJson(value ?? "") + "\", ";
        }

        private static string JsonBoolPair(string key, bool value)
        {
            return "\"" + key + "\": " + (value ? "true" : "false") + ", ";
        }

        private static string EscapeJson(string s)
        {
            return s.Replace("\\", "\\\\")
                    .Replace("\"", "\\\"")
                    .Replace("\n", "\\n")
                    .Replace("\r", "\\r")
                    .Replace("\t", "\\t");
        }
    }

    internal struct TelemetryEntry
    {
        public string Key;
        public string Description;
        public string Units;
        public bool Plotable;
        public bool IsAction;
        public bool AlwaysEvaluable;
        public string Category;
        public string ReturnType;
        public string Params;
        public string Since;
        public string RequiresMod;
        public bool Deprecated;
        public string DeprecatedMessage;
        public string Formatter;
        public string DeclaringClass;
        public string SourceFile;
    }
}
