#!/usr/bin/env bun
/**
 * Generates an OpenAPI 3.1 spec from the Telemachus API schema.
 *
 * Reads:
 *   - publish/api-schema.json  (generated by source generator at build time)
 *   - tools/manual-apis.json   (hand-maintained for constructor-registered APIs)
 *
 * Writes:
 *   - docs/openapi.yaml
 */

import { readFileSync, writeFileSync, mkdirSync } from "fs";
import { resolve, dirname } from "path";

const root = resolve(dirname(new URL(import.meta.url).pathname), "..");

interface ApiEntry {
  key: string;
  description: string;
  units?: string;
  plotable?: boolean;
  isAction?: boolean;
  alwaysEvaluable?: boolean;
  category?: string;
  returnType?: string;
  params?: string;
  since?: string;
  requiresMod?: string;
  deprecated?: boolean;
  deprecatedMessage?: string;
  formatter?: string;
  declaringClass?: string;
  sourceFile?: string;
}

// --- Load sources ---

let generated: ApiEntry[] = [];
try {
  const schemaPath = resolve(root, "publish/api-schema.json");
  generated = JSON.parse(readFileSync(schemaPath, "utf-8"));
  console.log(`Loaded ${generated.length} entries from api-schema.json`);
} catch (e) {
  console.warn("Warning: publish/api-schema.json not found — using manual-apis.json only");
}

const manualPath = resolve(root, "tools/manual-apis.json");
const manual: ApiEntry[] = JSON.parse(readFileSync(manualPath, "utf-8"));
console.log(`Loaded ${manual.length} entries from manual-apis.json`);

// Merge: manual entries fill gaps not covered by the source generator
const generatedKeys = new Set(generated.map((e) => e.key));
const all = [...generated, ...manual.filter((m) => !generatedKeys.has(m.key))];
all.sort((a, b) => a.key.localeCompare(b.key));

console.log(`Total: ${all.length} API entries`);

// --- Category metadata ---

const categoryLabels: Record<string, string> = {
  vessel: "Vessel",
  orbit: "Orbital Mechanics",
  navigation: "Navigation (Attitude)",
  flight: "Flight Controls",
  fbw: "Fly-by-Wire",
  timewarp: "Time Warp",
  target: "Target",
  docking: "Docking",
  deltav: "Delta-V",
  resource: "Resources",
  sensor: "Sensors",
  alarm: "Alarm Clock",
  body: "Celestial Bodies",
  map: "Map View",
  maneuver: "Maneuver Nodes",
  system: "System / Meta",
  mechjeb: "MechJeb (mod)",
  far: "FAR Aerodynamics (mod)",
  realchute: "RealChute (mod)",
  astrogator: "Astrogator (mod)",
  principia: "Principia N-Body Physics (mod)",
  landing: "Landing Prediction",
  thermal: "Thermal",
  science: "Science",
  career: "Career",
  comms: "Communications",
};

// --- Map C# types to JSON Schema ---

function toJsonSchema(returnType?: string): { type: string; items?: object } {
  switch (returnType) {
    case "double":
      return { type: "number" };
    case "int":
      return { type: "integer" };
    case "float":
      return { type: "number" };
    case "bool":
      return { type: "boolean" };
    case "string":
      return { type: "string" };
    case "string[]":
      return { type: "array", items: { type: "string" } };
    case "Vector3d":
      return { type: "array", items: { type: "number" } };
    case "object":
      return { type: "object" };
    default:
      return { type: "string" };
  }
}

// --- Parse params string into structured list ---

interface ParamInfo {
  name: string;
  type: string;
  optional: boolean;
}

function parseParams(params?: string): ParamInfo[] {
  if (!params) return [];
  return params.split(",").map((p) => {
    const trimmed = p.trim();
    const optional = trimmed.includes("?");
    const clean = trimmed.replace("?", "");
    const parts = clean.split(/\s+/);
    if (parts.length >= 2) {
      return { type: parts[0], name: parts.slice(1).join(""), optional };
    }
    return { type: "string", name: parts[0], optional };
  });
}

function paramToSchema(type: string): object {
  const s = toJsonSchema(type);
  return s;
}

// --- Build OpenAPI spec ---

// Group by category
const grouped = new Map<string, ApiEntry[]>();
for (const entry of all) {
  const cat = entry.category ?? inferCategory(entry.key);
  if (!grouped.has(cat)) grouped.set(cat, []);
  grouped.get(cat)!.push(entry);
}

function inferCategory(key: string): string {
  const prefix = key.split(".")[0];
  const map: Record<string, string> = {
    v: "vessel",
    o: "orbit",
    n: "navigation",
    f: "flight",
    t: "timewarp",
    tar: "target",
    dock: "docking",
    dv: "deltav",
    r: "resource",
    s: "sensor",
    alarm: "alarm",
    b: "body",
    m: "map",
    mj: "mechjeb",
    far: "far",
    rc: "realchute",
    astg: "astrogator",
    principia: "principia",
    a: "system",
    p: "system",
  };
  return map[prefix] ?? "other";
}

// Build tags
const tags = [...grouped.keys()]
  .sort()
  .map((cat) => ({
    name: cat,
    description: categoryLabels[cat] ?? cat,
    ...(grouped.get(cat)?.some((e) => e.requiresMod)
      ? { "x-requires-mod": grouped.get(cat)![0].requiresMod }
      : {}),
  }));

// Build paths — Telemachus uses a single endpoint with key-based dispatch
// We model each API key as a separate path for documentation clarity
const paths: Record<string, object> = {};

for (const entry of all) {
  const cat = entry.category ?? inferCategory(entry.key);
  const params = parseParams(entry.params);
  const method = entry.isAction ? "post" : "get";

  // Each API key becomes a literal path segment (not a path parameter)
  const pathKey = `/api/${entry.key}`;

  const parameters: object[] = [];
  if (params.length > 0) {
    // Params are passed via bracket notation: key[param1,param2]
    for (const p of params) {
      parameters.push({
        name: p.name,
        in: "query",
        required: !p.optional,
        description: `${p.type} parameter (passed via bracket notation)`,
        schema: paramToSchema(p.type),
      });
    }
  }

  const responseSchema = toJsonSchema(entry.returnType);

  const operation: Record<string, unknown> = {
    summary: entry.description,
    operationId: entry.key,
    tags: [cat],
    parameters: parameters.length > 0 ? parameters : undefined,
    responses: {
      "200": {
        description: "Successful response",
        content: {
          "application/json": {
            schema: {
              type: "object",
              properties: {
                [entry.key]: responseSchema,
              },
            },
          },
        },
      },
    },
  };

  if (entry.requiresMod) {
    operation["x-requires-mod"] = entry.requiresMod;
  }
  if (entry.deprecated) {
    operation.deprecated = true;
    if (entry.deprecatedMessage) {
      operation["x-deprecated-message"] = entry.deprecatedMessage;
    }
  }
  if (entry.units && entry.units !== "UNITLESS") {
    operation["x-units"] = entry.units;
  }
  if (entry.plotable) {
    operation["x-plotable"] = true;
  }
  if (entry.since) {
    operation["x-since"] = entry.since;
  }

  paths[pathKey] = { [method]: operation };
}

const spec = {
  openapi: "3.1.0",
  info: {
    title: "Telemachus Reborn API",
    description: [
      "Real-time telemetry API for Kerbal Space Program.",
      "",
      "## REST API",
      "",
      "Each telemetry key has its own endpoint:",
      "",
      "```",
      "GET /api/v.altitude        → { \"v.altitude\": 12500.0 }",
      "GET /api/o.PeA             → { \"o.PeA\": 75000.0 }",
      "GET /api/o.orbitalSpeedAt?1200.0  → pass args via query string",
      "```",
      "",
      "## Batch API",
      "",
      "Query multiple keys in a single call:",
      "",
      "```",
      "GET /telemachus/datalink?key1=v.altitude&key2=o.PeA",
      "```",
      "",
      "Returns all values as properties in one JSON object.",
      "Parameters are passed via bracket notation: `key1=o.orbitalSpeedAt[1200.0]`",
      "",
      "## WebSocket Streaming",
      "",
      "Connect to `ws://host:8085/datalink` and send subscription commands:",
      '```json',
      '{ "+": ["v.altitude", "o.PeA"], "rate": 500 }',
      '```',
      "",
      "## Mod Integrations",
      "",
      "Endpoints tagged with `x-requires-mod` are only available when the corresponding mod is installed.",
      "Query `a.mods` to check which mods are detected at runtime.",
    ].join("\n"),
    version: "1.7.0",
    license: {
      name: "MIT",
      url: "https://github.com/TeleIO/Telemachus-1/blob/main/LICENSE",
    },
  },
  servers: [
    {
      url: "http://localhost:8085",
      description: "Local KSP instance (default port)",
    },
  ],
  tags,
  paths,
};

// --- Write YAML output ---
// Simple YAML serializer sufficient for OpenAPI specs

function toYaml(obj: unknown, indent = 0): string {
  const pad = "  ".repeat(indent);

  if (obj === null || obj === undefined) return "null";
  if (typeof obj === "boolean") return obj ? "true" : "false";
  if (typeof obj === "number") return String(obj);
  if (typeof obj === "string") {
    if (
      obj.includes("\n") ||
      obj.includes(":") ||
      obj.includes("#") ||
      obj.includes("{") ||
      obj.includes("[") ||
      obj.includes('"') ||
      obj.includes("'") ||
      obj.startsWith(" ") ||
      obj.endsWith(" ") ||
      obj === "" ||
      obj === "true" ||
      obj === "false" ||
      obj === "null"
    ) {
      // Use block scalar for multiline, quoted for single-line
      if (obj.includes("\n")) {
        const lines = obj.split("\n");
        return (
          "|\n" + lines.map((l) => pad + "  " + l).join("\n")
        );
      }
      return JSON.stringify(obj);
    }
    return obj;
  }

  if (Array.isArray(obj)) {
    if (obj.length === 0) return "[]";
    return obj
      .map((item) => {
        const val = toYaml(item, indent + 1);
        if (typeof item === "object" && item !== null && !Array.isArray(item)) {
          // Object items: put first key on same line as dash
          const firstNewline = val.indexOf("\n");
          if (firstNewline === -1) return `${pad}- ${val}`;
          return `${pad}- ${val.trimStart()}`;
        }
        return `${pad}- ${val}`;
      })
      .join("\n");
  }

  if (typeof obj === "object") {
    const entries = Object.entries(obj as Record<string, unknown>).filter(
      ([, v]) => v !== undefined
    );
    if (entries.length === 0) return "{}";
    return entries
      .map(([key, val]) => {
        const yamlKey = key.includes("/") || key.includes("{") ? JSON.stringify(key) : key;
        if (
          typeof val === "object" &&
          val !== null
        ) {
          return `${pad}${yamlKey}:\n${toYaml(val, indent + 1)}`;
        }
        return `${pad}${yamlKey}: ${toYaml(val, indent)}`;
      })
      .join("\n");
  }

  return String(obj);
}

const yaml = toYaml(spec);

const outDir = resolve(root, "docs");
mkdirSync(outDir, { recursive: true });
const outPath = resolve(outDir, "openapi.yaml");
writeFileSync(outPath, yaml + "\n");
console.log(`Written ${outPath}`);

// Also write the merged JSON for easy consumption
const mergedJsonPath = resolve(outDir, "api-schema.json");
writeFileSync(mergedJsonPath, JSON.stringify(all, null, 2) + "\n");
console.log(`Written ${mergedJsonPath}`);
